In [3]:
import numpy as np
from numpy import linalg as LA
import math

In [4]:
N = 10
A = np.zeros((N,N))
for i in range(N):
    for j in range(N):
        if (i != j):
            A[i][j] = (1)/(i+1+j+1)
        else:
            A[i][j] = 1

In [5]:
print(A)

[[1.         0.33333333 0.25       0.2        0.16666667 0.14285714
  0.125      0.11111111 0.1        0.09090909]
 [0.33333333 1.         0.2        0.16666667 0.14285714 0.125
  0.11111111 0.1        0.09090909 0.08333333]
 [0.25       0.2        1.         0.14285714 0.125      0.11111111
  0.1        0.09090909 0.08333333 0.07692308]
 [0.2        0.16666667 0.14285714 1.         0.11111111 0.1
  0.09090909 0.08333333 0.07692308 0.07142857]
 [0.16666667 0.14285714 0.125      0.11111111 1.         0.09090909
  0.08333333 0.07692308 0.07142857 0.06666667]
 [0.14285714 0.125      0.11111111 0.1        0.09090909 1.
  0.07692308 0.07142857 0.06666667 0.0625    ]
 [0.125      0.11111111 0.1        0.09090909 0.08333333 0.07692308
  1.         0.06666667 0.0625     0.05882353]
 [0.11111111 0.1        0.09090909 0.08333333 0.07692308 0.07142857
  0.06666667 1.         0.05882353 0.05555556]
 [0.1        0.09090909 0.08333333 0.07692308 0.07142857 0.06666667
  0.0625     0.05882353 1.      

In [6]:
F = np.array([1/(i+1) for i in range(N)])

In [7]:
print(F)

[1.         0.5        0.33333333 0.25       0.2        0.16666667
 0.14285714 0.125      0.11111111 0.1       ]


In [8]:
def yakob(A,X,F,N):
    Y = np.zeros(N)
    for i in range(N):
        for j in range(N):
            if j == i:
                continue
            Y[i] += -(X[j]*(A[i][j]))
        Y[i] += F[i]
        Y[i] = Y[i]/(A[i][i])
    X = Y
    return X

In [9]:
X = np.zeros(N)
for i in range(100):
    X = yakob(A,X,F,N)
    print(X)

[1.         0.5        0.33333333 0.25       0.2        0.16666667
 0.14285714 0.125      0.11111111 0.1       ]
[ 0.59090909 -0.03787879 -0.13850039 -0.15893482 -0.15881452 -0.15248432
 -0.14440633 -0.13615216 -0.12829348 -0.12101969]
[1.18430083 0.45037623 0.29949974 0.23379843 0.19549949 0.16965599
 0.15067898 0.13597214 0.1241445  0.11437261]
[ 0.6146653  -0.09392503 -0.17607727 -0.18614446 -0.18006956 -0.16997404
 -0.15932037 -0.14919568 -0.13991513 -0.13152159]
[1.22929052 0.4646236  0.3177107  0.25195388 0.21263354 0.18560654
 0.16549841 0.14976634 0.13702477 0.12644126]
[ 0.59082773 -0.12523391 -0.20141951 -0.20796694 -0.19936751 -0.18731692
 -0.17508806 -0.1636612  -0.15328353 -0.14395167]
[1.26216584 0.49164936 0.34235061 0.27399346 0.23245855 0.20359218
 0.18194826 0.16491958 0.15107052 0.13953075]
[ 0.55904325 -0.15558471 -0.22786845 -0.23134124 -0.2202838  -0.20623784
 -0.19236157 -0.17955297 -0.16800014 -0.15765662]
[1.29640141 0.52277125 0.3698756  0.29840897 0.2543419  

In [10]:
print(F - A@X)

[56.83327833 52.29301647 46.07677988 40.83509114 36.58572458 33.11827924
 30.24805496 27.83699812 25.78432646 24.0159702 ]


In [11]:
def zeid(A,X,F,N):
    for i in range(N):
        X[i] = 0
        for j in range(N):
            if j == i:
                continue
            X[i] += -(X[j]*(A[i][j]))
        X[i] += F[i]
        X[i] = X[i]/(A[i][i])
    return X

In [13]:
X = np.zeros(N)
for i in range(8):
    X = zeid(A,X,F,N)
    print(X)

[ 1.          0.16666667  0.05        0.01507937  0.00159832 -0.0042326
 -0.00683984 -0.00794448 -0.0083042  -0.00828248]
[ 0.93258791  0.17992444  0.06505311  0.02696161  0.01044902  0.00223994
 -0.00217152 -0.00464442 -0.00605036 -0.00683674]
[ 9.18322135e-01  1.76441170e-01  6.47273681e-02  2.78351443e-02
  1.17792574e-02  3.70579585e-03 -7.17632700e-04 -3.27104367e-03
 -4.78765514e-03 -5.69549015e-03]
[ 9.18394487e-01  1.75454571e-01  6.39894025e-02  2.73708730e-02
  1.15256356e-02  3.60482045e-03 -7.09758515e-04 -3.18612795e-03
 -4.64869438e-03 -5.51919755e-03]
[ 9.19017053e-01  1.75484184e-01  6.39034372e-02  2.72609091e-02
  1.14209209e-02  3.51529504e-03 -7.81379748e-04 -3.24002831e-03
 -4.68620413e-03 -5.54203690e-03]
[ 9.19101676e-01  1.75536308e-01  6.39275471e-02  2.72679598e-02
  1.14180288e-02  3.50685693e-03 -7.92629879e-04 -3.25237216e-03
 -4.69855610e-03 -5.55371399e-03]
[ 9.19083626e-01  1.75542376e-01  6.39353127e-02  2.72744500e-02
  1.14227934e-02  3.51003241e-03 -

In [39]:
print(F - A@X)

[5.19511767e-08 4.48928608e-08 2.98615111e-08 1.86871258e-08
 1.12129638e-08 6.38263395e-09 3.34612676e-09 1.51364790e-09
 4.87542048e-10 0.00000000e+00]


In [ ]:
A = np.array()

In [40]:
#Метод Гаусса
    #Прямой ход метода Гаусса
def gauss_1(A,F,N):
    C = A.copy()
    L = F.copy()
    for i in range(N):
        for j in range(i+1,N):
            coef = C[j][i]/C[i][i]
            L[j] -= L[i]*coef
            for k in range(i,N):
                C[j][k] -= C[i][k]*coef
    return C, L

In [41]:
B,L = gauss_1(A,F,N) #применение прямого хода

In [42]:
#Обратный ход метода Гаусса
def gauss_2(B,L,N):
    D = B.copy()
    K = L.copy()
    for i in reversed(range(N)):
        for j in range(0,i):
            coef = D[j][i]/D[i][i]
            K[j] -= K[i]*coef
            for k in range(0,i+1):
                D[j][k] -= D[i][k]*coef
    return D, K

In [43]:
#Применение обратного хода метода Гаусса

R, J = gauss_2(B,L,N)
Sol = np.zeros(N)
for i in range(N):
    Sol[i] = J[i]/R[i][i]

In [44]:
Sol

array([ 9.19077109e-01,  1.75540170e-01,  6.39348240e-02,  2.72747640e-02,
        1.14234685e-02,  3.51083928e-03, -7.89957814e-04, -3.25080145e-03,
       -4.69787781e-03, -5.55373994e-03])

In [45]:
c_2 = np.linalg.solve(A,F)
print(c_2)
-3.25083555e-03

[ 9.19077109e-01  1.75540170e-01  6.39348240e-02  2.72747640e-02
  1.14234685e-02  3.51083928e-03 -7.89957814e-04 -3.25080145e-03
 -4.69787781e-03 -5.55373994e-03]


In [13]:
def scal(x,y):
    m = x@(y.transpose())
    return m

In [49]:
u = F
for j in range(10):
    u = A@u
print("lambda",scal(u,A@u)/scal(u,u))

lambda 2.048359886305534


In [15]:
np.linalg.eig(A)


(array([2.04835993, 0.65795975, 0.81224305, 0.86881409, 0.97922572,
        0.89874464, 0.91743388, 0.93029794, 0.94715386, 0.93976714]),
 array([[-0.46216713, -0.77735393,  0.23695559,  0.14589392, -0.2778007 ,
         -0.10615482,  0.08301494, -0.06715745, -0.04302458, -0.05472317],
        [-0.42524581,  0.60113125,  0.54239602,  0.20934951, -0.28464081,
         -0.13291509,  0.09745506, -0.07596145, -0.04670333, -0.06042278],
        [-0.37469549,  0.1644828 , -0.79346119,  0.34137097, -0.21790083,
         -0.14613546,  0.09354801, -0.06804655, -0.03900521, -0.0519094 ],
        [-0.33207018,  0.07388381, -0.13094577, -0.89967183, -0.123458  ,
         -0.17780773,  0.07985497, -0.05053205, -0.02553223, -0.03570322],
        [-0.29751441,  0.03731656, -0.04005077, -0.06082304, -0.01650759,
          0.94961656,  0.04690064, -0.01949536, -0.00668744, -0.0109802 ],
        [-0.26931721,  0.01887848, -0.00714327,  0.00579631,  0.09749927,
         -0.03456174, -0.95495671,  0.05491

In [16]:
u = np.array([1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0])
for j in range(10):
    u = A@u/LA.norm(u, 2)
print("Eigenvalue max",scal(u,A@u)/scal(u,u))
Eigen_Value_Max = scal(u,A@u)/scal(u,u)

Eigenvalue max 2.0483598954823554


In [17]:
u = F
B = LA.inv(A)
for j in range(10):
    u = B@u
print("Eigenvalue min",scal(u,u)/scal(u,B@u))
Eigen_Value_Min = scal(u,u)/scal(u,B@u)

Eigenvalue min 0.6586729937583621


In [18]:
print('Число обусловленности в случае евклидовой нормы', Eigen_Value_Max/Eigen_Value_Min)

Число обусловленности в случае евклидовой нормы 3.109828268188885


In [19]:
#Кубическая:
print('Чило обусловленности в случае кубической нормы:',LA.norm(A, np.inf)* LA.norm(LA.inv(A),np.inf))
#Октаэдрическая:
print('Число обусловленности в случае октаэдрической нормы:',LA.norm(A, 1)* LA.norm(LA.inv(A), 1))


Чило обусловленности в случае кубической нормы: 5.6336089382284
Число обусловленности в случае октаэдрической нормы: 5.6336089382284005


In [20]:

#Осталось выписать критерий остановки метода Зейделя |u_s - u_s+1| <= (1-q)*\epsilon для невязки, 
#где q - норма матрицы перехода в методе Зейделя. Для этого надо представить A = L + D + U и пложить
# R = - (L+D)^(-1)U


In [21]:
N = 10
L = np.zeros((N,N))
D = np.zeros((N,N))
U = np.zeros((N,N))
for i in range(N):
    for j in range(N):
        if (i == j):
            D[i][j] = A[i][j]
        else:
            if (i > j):
                L[i][j] = A[i][j]
            else:
                U[i][j] = A[i][j]

In [22]:
print(L)
print(D)
print(U)

[[0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.        ]
 [0.33333333 0.         0.         0.         0.         0.
  0.         0.         0.         0.        ]
 [0.25       0.2        0.         0.         0.         0.
  0.         0.         0.         0.        ]
 [0.2        0.16666667 0.14285714 0.         0.         0.
  0.         0.         0.         0.        ]
 [0.16666667 0.14285714 0.125      0.11111111 0.         0.
  0.         0.         0.         0.        ]
 [0.14285714 0.125      0.11111111 0.1        0.09090909 0.
  0.         0.         0.         0.        ]
 [0.125      0.11111111 0.1        0.09090909 0.08333333 0.07692308
  0.         0.         0.         0.        ]
 [0.11111111 0.1        0.09090909 0.08333333 0.07692308 0.07142857
  0.06666667 0.         0.         0.        ]
 [0.1        0.09090909 0.08333333 0.07692308 0.07142857 0.06666667
  0.0625     0.05882353 0.         0.        ]
 [0.09090909 

In [23]:
R = -LA.inv(L+D)@U

In [24]:
C = R@R.transpose()
u= F
for j in range(100):
    u = C@u/LA.norm(u, 2)
    
print((scal(u,C@u)/scal(u,u)))
norm = math.sqrt((scal(u,C@u)/scal(u,u)))
print("Евклидова норма:",norm)

0.337299803961558
Евклидова норма: 0.5807751750561985
